apiVersion: v1
kind: Service
metadata:
  name: gamingsite-service
spec:
  type: LoadBalancer
  selector:
    app: gamingsite-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
